// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehpusnjivjdnipdhkzpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVocHVzbmppdmpkbmlwZGhrenBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDczMDAsImV4cCI6MjA2NDY4MzMwMH0.0lvBwLRJCWmXBhrp6dMnmkh1yPWhx2bnGPYSp0JZFLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);